(
SetProperty photometricLight_ActiveLight #type "Free_Point"
SetProperty photometricLight_ActiveLight #useKelvin on
SetProperty photometricLight_ActiveLight #kelvin 2750
SetProperty photometricLight_ActiveLight #distribution 0
SetProperty photometricLight_ActiveLight #intensityType 1
SetProperty photometricLight_ActiveLight #Intensity 64
SetProperty photometricLight_ActiveLight #useMultiplier on
)