(
SetProperty photometricLight_ActiveLight #type "Free_Point"
SetProperty photometricLight_ActiveLight #useKelvin off
SetProperty photometricLight_ActiveLight #kelvin 2940.
SetProperty photometricLight_ActiveLight #distribution 3
SetProperty photometricLight_ActiveLight #intensityType 0
SetProperty photometricLight_ActiveLight #webfile ((getDir #maxroot) + "sceneassets\\photometric\\point_recessed_wallwash_250W.ies")	--LOC NOTE: do not localize this
SetProperty photometricLight_ActiveLight #Flux 4010.0
SetProperty photometricLight_ActiveLight #useMultiplier on
)