(
SetProperty photometricLight_ActiveLight #type "Free_Point"
SetProperty photometricLight_ActiveLight #useKelvin off
SetProperty photometricLight_ActiveLight #kelvin 3200.
SetProperty photometricLight_ActiveLight #distribution 3
SetProperty photometricLight_ActiveLight #intensityType 0
SetProperty photometricLight_ActiveLight #webfile ((getDir #maxroot) + "sceneassets\\photometric\\point_recessed_wallwash_75W.ies")	--LOC NOTE: do not localize this
SetProperty photometricLight_ActiveLight #Flux 1200.0
SetProperty photometricLight_ActiveLight #useMultiplier on
)